apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: angular-app 
  namespace: example-namespaces
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app : angular-app
    spec:
      containers:
        - name: angular-app-container
          image: inyee/angular-app:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: angular-app
  name: angular-service
  namespace: example-namespaces
spec:
  type: NodePort
  ports:
  - name: angular-app
    port: 80
    protocol: TCP
  selector:
    app: angular-app          

